# Generated by Django 4.2.4 on 2023-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
