# Generated by Django 4.2.4 on 2023-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='premium_member',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='auth_provider',
            field=models.CharField(default='AppUser', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
