# Generated by Django 4.2.5 on 2023-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_paystack_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='no_of_post',
            field=models.IntegerField(default=0),
        ),
    ]
