# Generated by Django 4.2.4 on 2023-09-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_bio_appuser_premium_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
