# Generated by Django 4.2.4 on 2023-08-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
