# Generated by Django 4.2.4 on 2023-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='auth_provider',
            field=models.CharField(default='AppUser', max_length=20),
        ),
    ]
