# Generated by Django 4.2.4 on 2023-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_appuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(default='/media/user_profile_pic/Profile_Image_Placeholder-small.jpg', upload_to='user_profile_pics/'),
        ),
    ]
