# Generated by Django 4.2.4 on 2023-09-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_pic',
        ),
    ]
