# Generated by Django 4.2.4 on 2023-09-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(default='user_profile_pics/Profile_Image_Placeholder-small.jpg', upload_to='user_profile_pics'),
        ),
    ]
