# Generated by Django 4.2.4 on 2023-09-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_remove_appuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_pics'),
        ),
    ]
