# Generated by Django 4.2.4 on 2023-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='auth_provider',
            field=models.CharField(default='AppUser', max_length=20),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='premium_member',
            field=models.BooleanField(default=False),
        ),
    ]
