# Generated by Django 4.2.4 on 2023-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0013_alter_appuser_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
