# Generated by Django 4.2.4 on 2023-09-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0014_alter_appuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='auth_provider',
            field=models.CharField(default='AppUser', max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
