# Generated by Django 4.2.4 on 2023-09-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0015_alter_appuser_auth_provider_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
