# Generated by Django 4.2.5 on 2023-10-06 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999)),
                ('heroImage', models.ImageField(upload_to='heroImages')),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False, max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user_articles',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_title'),
        ),
    ]
