# Generated by Django 4.2.5 on 2023-10-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserArticles', '0005_alter_user_articles_heroimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_articles',
            name='no_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
