# Generated by Django 4.2.5 on 2023-10-25 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserArticles", "0006_user_articles_no_of_views"),
    ]
