# Generated by Django 4.2.4 on 2023-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailVerification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='date_sent',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
