# Generated by Django 4.2.4 on 2023-08-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailVerification', '0002_remove_emailverification_date_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='code_is_for',
            field=models.CharField(default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
