# Generated by Django 4.2.4 on 2023-08-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailVerification', '0003_emailverification_code_is_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='code_is_for',
        ),
    ]
